export const testMenu = [
  {
    code: "AG-FULL-01",
    name: "Agilus Platinum Full Body Checkup | Mohali",
    mrp: "2999",
    method: "Comprehensive Wellness Panel",
    tat: "24 Hours",
    sample: "Blood/Urine (Free Home Collection)",
    preparation: "10-12 hours fasting required.",
  },
  {
    code: "AG-DIAB-01",
    name: "Agilus Diabetes Monitoring Package | Mohali",
    mrp: "899",
    method: "HbA1c & Glucose Analysis",
    tat: "12 Hours",
    sample: "Blood (Free Home Collection)",
    preparation: "No specific prep required.",
  },
  {
    code: "AG-THYR-01",
    name: "Agilus Advanced Thyroid Profile (T3, T4, TSH)",
    mrp: "650",
    method: "CLIA",
    tat: "12-24 Hours",
    sample: "Blood (Free Home Collection Available)",
    preparation: "Early morning sample preferred.",
  },
  {
    code: "AG-LIPID-01",
    name: "Agilus Heart Health & Lipid Profile",
    mrp: "550",
    method: "Spectrophotometry",
    tat: "24 Hours",
    sample: "Blood (Free Home Collection)",
    preparation: "10-12 hours fasting recommended.",
  },
  {
    code: "AG-VIT-01",
    name: "Agilus Vitamin D & B12 Combo Test",
    mrp: "1400",
    method: "CLIA",
    tat: "24-48 Hours",
    sample: "Blood (Free Home Collection)",
    preparation: "No specific prep required.",
  },
  {
    code: "AG-CBC-01",
    name: "Agilus Complete Blood Count (CBC)",
    mrp: "350",
    method: "Automated Hematology Analyzer",
    tat: "12 Hours",
    sample: "Blood (Free Home Collection)",
    preparation: "No specific prep required.",
  },
  {
    code: "AG-KFT-01",
    name: "Agilus Kidney Function Test (KFT)",
    mrp: "700",
    method: "Automated Biochemistry",
    tat: "24 Hours",
    sample: "Blood (Free Home Collection)",
    preparation: "No specific prep required.",
  },
  {
    code: "AG-LFT-01",
    name: "Agilus Liver Function Test (LFT)",
    mrp: "750",
    method: "Automated Biochemistry",
    tat: "24 Hours",
    sample: "Blood (Free Home Collection)",
    preparation: "10-12 hours fasting for best results.",
  },
];
